# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lend' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lend
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'SDWebImage'
  pod 'Stripe'

end
